#!/bin/bash

chmod +x /home/$USER/start.neo4j 
chmod +x /home/$USER/start.vscode

# starting neo4j
/home/$USER/start.neo4j   &
/home/$USER/start.vscode   &

# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"